// <auto-generated />
using System;
using DorucovaciSluzba.Infrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DorucovaciSluzba.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251202174652_PackageHistory")]
    partial class PackageHistory
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("DorucovaciSluzba.Domain.Entities.PackageHistoryItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DatumZmeny")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("StavId")
                        .HasColumnType("int");

                    b.Property<int>("ZasilkaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StavId");

                    b.ToTable("PackageHistoryItem");
                });

            modelBuilder.Entity("DorucovaciSluzba.Domain.Entities.StavZasilka", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Stav")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("StavZasilka");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Stav = "Objednávka vytvořena"
                        },
                        new
                        {
                            Id = 2,
                            Stav = "Zásilka je v přepravě"
                        },
                        new
                        {
                            Id = 3,
                            Stav = "Doručeno"
                        },
                        new
                        {
                            Id = 4,
                            Stav = "Reklamováno"
                        });
                });

            modelBuilder.Entity("DorucovaciSluzba.Domain.Entities.Zasilka", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Cislo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("DatumOdeslani")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<DateTime>("DatumOdeslani"));

                    b.Property<string>("DestinaceCP")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("DestinaceMesto")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("DestinacePsc")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("DestinaceUlice")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("KuryrId")
                        .HasColumnType("int");

                    b.Property<int>("OdesilatelId")
                        .HasColumnType("int");

                    b.Property<int>("PrijemceId")
                        .HasColumnType("int");

                    b.Property<int>("StavId")
                        .HasColumnType("int");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("KuryrId");

                    b.HasIndex("OdesilatelId");

                    b.HasIndex("PrijemceId");

                    b.HasIndex("StavId");

                    b.HasIndex("UserId");

                    b.ToTable("Zasilka");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Cislo = "123-45-67",
                            DatumOdeslani = new DateTime(2025, 11, 20, 10, 30, 0, 0, DateTimeKind.Unspecified),
                            DestinaceCP = "456",
                            DestinaceMesto = "Brno",
                            DestinacePsc = "602 00",
                            DestinaceUlice = "Nádražní",
                            KuryrId = 4,
                            OdesilatelId = 7,
                            PrijemceId = 8,
                            StavId = 3
                        },
                        new
                        {
                            Id = 2,
                            Cislo = "234-56-78",
                            DatumOdeslani = new DateTime(2025, 11, 23, 14, 15, 0, 0, DateTimeKind.Unspecified),
                            DestinaceCP = "789",
                            DestinaceMesto = "Ostrava",
                            DestinacePsc = "700 30",
                            DestinaceUlice = "Zahradní",
                            KuryrId = 4,
                            OdesilatelId = 7,
                            PrijemceId = 9,
                            StavId = 2
                        },
                        new
                        {
                            Id = 3,
                            Cislo = "345-67-89",
                            DatumOdeslani = new DateTime(2025, 11, 24, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            DestinaceCP = "321",
                            DestinaceMesto = "Plzeň",
                            DestinacePsc = "301 00",
                            DestinaceUlice = "Školní",
                            OdesilatelId = 9,
                            PrijemceId = 11,
                            StavId = 1
                        },
                        new
                        {
                            Id = 4,
                            Cislo = "456-78-90",
                            DatumOdeslani = new DateTime(2025, 11, 22, 16, 45, 0, 0, DateTimeKind.Unspecified),
                            DestinaceCP = "123",
                            DestinaceMesto = "Praha",
                            DestinacePsc = "110 00",
                            DestinaceUlice = "Hlavní",
                            KuryrId = 4,
                            OdesilatelId = 10,
                            PrijemceId = 11,
                            StavId = 2
                        },
                        new
                        {
                            Id = 5,
                            Cislo = "567-89-01",
                            DatumOdeslani = new DateTime(2025, 11, 18, 11, 20, 0, 0, DateTimeKind.Unspecified),
                            DestinaceCP = "789",
                            DestinaceMesto = "Ostrava",
                            DestinacePsc = "700 30",
                            DestinaceUlice = "Zahradní",
                            KuryrId = 5,
                            OdesilatelId = 8,
                            PrijemceId = 10,
                            StavId = 3
                        },
                        new
                        {
                            Id = 6,
                            Cislo = "678-90-12",
                            DatumOdeslani = new DateTime(2025, 11, 15, 8, 30, 0, 0, DateTimeKind.Unspecified),
                            DestinaceCP = "123",
                            DestinaceMesto = "Praha",
                            DestinacePsc = "110 00",
                            DestinaceUlice = "Hlavní",
                            KuryrId = 5,
                            OdesilatelId = 11,
                            PrijemceId = 7,
                            StavId = 2
                        },
                        new
                        {
                            Id = 7,
                            Cislo = "789-01-23",
                            DatumOdeslani = new DateTime(2025, 11, 15, 8, 30, 0, 0, DateTimeKind.Unspecified),
                            DestinaceCP = "300",
                            DestinaceMesto = "Zlín",
                            DestinacePsc = "760 01",
                            DestinaceUlice = "Školní",
                            KuryrId = 6,
                            OdesilatelId = 7,
                            PrijemceId = 10,
                            StavId = 2
                        });
                });

            modelBuilder.Entity("DorucovaciSluzba.Infrastructure.Identity.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ConcurrencyStamp = "9cf14c2c-19e7-40d6-b744-8917505c3106",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = 2,
                            ConcurrencyStamp = "3ea1f7bc-4de1-5fg9-d4e8-5890e8cdb4ff",
                            Name = "Podpora",
                            NormalizedName = "PODPORA"
                        },
                        new
                        {
                            Id = 3,
                            ConcurrencyStamp = "be0efcde-9d0a-461d-8eb6-444b043d6660",
                            Name = "Kuryr",
                            NormalizedName = "KURYR"
                        },
                        new
                        {
                            Id = 4,
                            ConcurrencyStamp = "29dafca7-cd20-4cd9-a3dd-4779d7bac3ee",
                            Name = "Uzivatel",
                            NormalizedName = "UZIVATEL"
                        });
                });

            modelBuilder.Entity("DorucovaciSluzba.Infrastructure.Identity.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("CP")
                        .HasColumnType("longtext");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("DatumNarozeni")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("FirstName")
                        .HasColumnType("longtext");

                    b.Property<string>("LastName")
                        .HasColumnType("longtext");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Mesto")
                        .HasColumnType("longtext");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("longtext");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Psc")
                        .HasColumnType("longtext");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("longtext");

                    b.Property<string>("Telefon")
                        .HasColumnType("longtext");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Ulice")
                        .HasColumnType("longtext");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "b09a83ae-cfd3-4ee7-97e6-fbcf0b0fe78c",
                            Email = "admin@kuryr.cz",
                            EmailConfirmed = true,
                            FirstName = "Admin",
                            LastName = "Admin",
                            LockoutEnabled = true,
                            NormalizedEmail = "ADMIN@KURYR.CZ",
                            NormalizedUserName = "ADMIN",
                            PasswordHash = "AQAAAAIAAYagAAAAEP88Q6YXU7RQG6LcDoHvZpXtdmv1Kh0hyoBkWJtFrTAYVz+OyRD1ZvzowRpa/sI4xg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "VGWVSB6MVQ7NB5QYDEG52OEBGMYC3CP5",
                            TwoFactorEnabled = false,
                            UserName = "admin"
                        },
                        new
                        {
                            Id = 2,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "cee2a6bf-19a7-4e22-8d24-1d13c8c50045",
                            Email = "mikydosh@kuryr.cz",
                            EmailConfirmed = true,
                            FirstName = "Mikydosh",
                            LastName = "Mikydosh",
                            LockoutEnabled = true,
                            NormalizedEmail = "MIKYDOSH@KURYR.CZ",
                            NormalizedUserName = "MIKYDOSH",
                            PasswordHash = "AQAAAAIAAYagAAAAEB0xgwR38FFdOSyzuCtsLKEgylMVI5QJJtX7SD4TNt+plq1SOFJIXSPV2HL2XZVzUw==",
                            PhoneNumber = "777 777 777",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "3TUBCJIIU3M7B4O2CBRAFMUJQ2LMEBID",
                            TwoFactorEnabled = false,
                            UserName = "Mikydosh"
                        },
                        new
                        {
                            Id = 3,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "038db544-65bc-4eb8-babd-2b62292f550f",
                            Email = "support@kuryr.cz",
                            EmailConfirmed = true,
                            FirstName = "Support",
                            LastName = "Support",
                            LockoutEnabled = true,
                            NormalizedEmail = "SUPPORT@KURYR.CZ",
                            NormalizedUserName = "SUPPORT",
                            PasswordHash = "AQAAAAIAAYagAAAAEIK3vTeRO8jtSHQeu22rjXmOAcOrnj5TTrUyLrC2PO/CLutEmOinp2XbeeZ8JzeztQ==",
                            PhoneNumber = "777 888 999",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "LZ6JM3OG3F3SHIPBSX5CXCHLIZOBAO7N",
                            Telefon = "777 888 999",
                            TwoFactorEnabled = false,
                            UserName = "support"
                        },
                        new
                        {
                            Id = 4,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "0f5ced05-1c9c-4ed4-bf45-560a91558b19",
                            Email = "petr.svoboda@email.cz",
                            EmailConfirmed = true,
                            FirstName = "Petr",
                            LastName = "Svoboda",
                            LockoutEnabled = true,
                            NormalizedEmail = "PETR.SVOBODA@EMAIL.CZ",
                            NormalizedUserName = "PETR.SVOBODA",
                            PasswordHash = "AQAAAAIAAYagAAAAEIwBb49OKla+4yeCCS1R94+d1xcujKitJWWBDa41PgsTXnvmJJfVoxkUZ2/+fVXjNA==",
                            PhoneNumber = "700 123 456",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "5LIJBOB6YT3NYVGTHLD3WFTPCHTTFEKQ",
                            Telefon = "700 123 456",
                            TwoFactorEnabled = false,
                            UserName = "petr.svoboda"
                        },
                        new
                        {
                            Id = 5,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "d20c95cg-ehg5-6gg9-d0g8-hdfhb21hg90e",
                            Email = "martin_vesely@seznam.cz",
                            EmailConfirmed = true,
                            FirstName = "Martin",
                            LastName = "Veselý",
                            LockoutEnabled = true,
                            NormalizedEmail = "MARTIN_VESELY@SEZNAM.CZ",
                            NormalizedUserName = "MARTIN_VESELY",
                            PasswordHash = "AQAAAAIAAYagAAAAEIwBb49OKla+4yeCCS1R94+d1xcujKitJWWBDa41PgsTXnvmJJfVoxkUZ2/+fVXjNA==",
                            PhoneNumber = "702 456 789",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "UNK27SYDWN7W5R2YEOCUUFERKXCP4ITS",
                            Telefon = "702 456 789",
                            TwoFactorEnabled = false,
                            UserName = "martin_vesely"
                        },
                        new
                        {
                            Id = 6,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "d20c95cg-ehg5-6gg9-d0g8-hdfhb21hg90e",
                            Email = "lukas.cerny@gmail.com",
                            EmailConfirmed = true,
                            FirstName = "Lukáš",
                            LastName = "Černý",
                            LockoutEnabled = true,
                            NormalizedEmail = "LUKAS.CERNY@GMAIL.COM",
                            NormalizedUserName = "LUKAS.CERNY",
                            PasswordHash = "AQAAAAIAAYagAAAAEIwBb49OKla+4yeCCS1R94+d1xcujKitJWWBDa41PgsTXnvmJJfVoxkUZ2/+fVXjNA==",
                            PhoneNumber = "702 456 789",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "A3LA2H6W6F4PZIAB2UHWRER4FVJJIVUM",
                            Telefon = "739 556 789",
                            TwoFactorEnabled = false,
                            UserName = "lukas.cerny"
                        },
                        new
                        {
                            Id = 7,
                            AccessFailedCount = 0,
                            CP = "123",
                            ConcurrencyStamp = "38882ce7-1365-4e87-b881-11156cb75c5a",
                            Email = "karel.prochazka@email.cz",
                            EmailConfirmed = true,
                            FirstName = "Karel",
                            LastName = "Procházka",
                            LockoutEnabled = true,
                            Mesto = "Praha",
                            NormalizedEmail = "KAREL.PROCHAZKA@EMAIL.CZ",
                            NormalizedUserName = "KAREL.PROCHAZKA",
                            PasswordHash = "AQAAAAIAAYagAAAAEOwdhKmr4UhpvNhElz/3Ed+laOZriqxPV8u5bk7WW3l0iZTV6jnyElweL1GXNZJkzQ==",
                            PhoneNumber = "603 111 222",
                            PhoneNumberConfirmed = false,
                            Psc = "110 00",
                            SecurityStamp = "56RHAYBYWWYNQZ3N53XH76OVIE6QGTPQ",
                            Telefon = "603 111 222",
                            TwoFactorEnabled = false,
                            Ulice = "Hlavní",
                            UserName = "karel.prochazka"
                        },
                        new
                        {
                            Id = 8,
                            AccessFailedCount = 0,
                            CP = "456",
                            ConcurrencyStamp = "6eee7fcd-c43b-42eb-acdb-909a007f85ee",
                            Email = "eva.malkova@email.cz",
                            EmailConfirmed = true,
                            FirstName = "Eva",
                            LastName = "Málková",
                            LockoutEnabled = true,
                            Mesto = "Brno",
                            NormalizedEmail = "EVA.MALKOVA@EMAIL.CZ",
                            NormalizedUserName = "EVA.MALKOVA",
                            PasswordHash = "AQAAAAIAAYagAAAAEOwdhKmr4UhpvNhElz/3Ed+laOZriqxPV8u5bk7WW3l0iZTV6jnyElweL1GXNZJkzQ==",
                            PhoneNumber = "604 333 444",
                            PhoneNumberConfirmed = false,
                            Psc = "602 00",
                            SecurityStamp = "B3FEHEGUWPYSIMP6TIN7X7XUBGLJTF2T",
                            Telefon = "604 333 444",
                            TwoFactorEnabled = false,
                            Ulice = "Nádražní",
                            UserName = "eva.malkova"
                        },
                        new
                        {
                            Id = 9,
                            AccessFailedCount = 0,
                            CP = "789",
                            ConcurrencyStamp = "2a59d5f9-9062-4722-b9f6-370de85ec0c7",
                            Email = "jana_horakova@email.cz",
                            EmailConfirmed = true,
                            FirstName = "Jana",
                            LastName = "Horáková",
                            LockoutEnabled = true,
                            Mesto = "Ostrava",
                            NormalizedEmail = "JANA_HORAKOVA@EMAIL.CZ",
                            NormalizedUserName = "JANA_HORAKOVA",
                            PasswordHash = "AQAAAAIAAYagAAAAEOwdhKmr4UhpvNhElz/3Ed+laOZriqxPV8u5bk7WW3l0iZTV6jnyElweL1GXNZJkzQ==",
                            PhoneNumber = "605 555 666",
                            PhoneNumberConfirmed = false,
                            Psc = "700 30",
                            SecurityStamp = "XNCJIJ2L3J6HVXENA6UKUV5ND4QGLJCA",
                            Telefon = "605 555 666",
                            TwoFactorEnabled = false,
                            Ulice = "Zahradní",
                            UserName = "jana_horakova"
                        },
                        new
                        {
                            Id = 10,
                            AccessFailedCount = 0,
                            CP = "321",
                            ConcurrencyStamp = "0f5ced05-1c9c-4ed4-bf45-560a91558b19",
                            Email = "paveldobry@gmail.com",
                            EmailConfirmed = true,
                            FirstName = "Pavel",
                            LastName = "Dobrý",
                            LockoutEnabled = true,
                            Mesto = "Plzeň",
                            NormalizedEmail = "PAVELDOBRY@GMAILL.COM",
                            NormalizedUserName = "PAVELDOBRY",
                            PasswordHash = "AQAAAAIAAYagAAAAEOwdhKmr4UhpvNhElz/3Ed+laOZriqxPV8u5bk7WW3l0iZTV6jnyElweL1GXNZJkzQ==",
                            PhoneNumber = "606 777 888",
                            PhoneNumberConfirmed = false,
                            Psc = "301 00",
                            SecurityStamp = "IAHFGXHAVOV3PM7P2TG7TNTHNJ4GBJD5",
                            Telefon = "606 777 888",
                            TwoFactorEnabled = false,
                            Ulice = "Školní",
                            UserName = "paveldobry"
                        },
                        new
                        {
                            Id = 11,
                            AccessFailedCount = 0,
                            CP = "321",
                            ConcurrencyStamp = "62667ef0-5589-4d42-9d78-575134d4442f",
                            Email = "katerina.dobra@gmail.com",
                            EmailConfirmed = true,
                            FirstName = "Kateřina",
                            LastName = "Dobrá",
                            LockoutEnabled = true,
                            Mesto = "Plzeň",
                            NormalizedEmail = "KATERINA.DOBRA@GMAILL.COM",
                            NormalizedUserName = "KATERINADOBRA",
                            PasswordHash = "AQAAAAIAAYagAAAAEOwdhKmr4UhpvNhElz/3Ed+laOZriqxPV8u5bk7WW3l0iZTV6jnyElweL1GXNZJkzQ==",
                            PhoneNumber = "609 654 888",
                            PhoneNumberConfirmed = false,
                            Psc = "301 00",
                            SecurityStamp = "B4PZVLZDNK7MKANXOJL4RRETNS5EHLFJ",
                            Telefon = "609 654 888",
                            TwoFactorEnabled = false,
                            Ulice = "Školní",
                            UserName = "katerina.dobra"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("longtext");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            RoleId = 1
                        },
                        new
                        {
                            UserId = 2,
                            RoleId = 1
                        },
                        new
                        {
                            UserId = 3,
                            RoleId = 2
                        },
                        new
                        {
                            UserId = 4,
                            RoleId = 3
                        },
                        new
                        {
                            UserId = 5,
                            RoleId = 3
                        },
                        new
                        {
                            UserId = 6,
                            RoleId = 3
                        },
                        new
                        {
                            UserId = 7,
                            RoleId = 4
                        },
                        new
                        {
                            UserId = 8,
                            RoleId = 4
                        },
                        new
                        {
                            UserId = 9,
                            RoleId = 4
                        },
                        new
                        {
                            UserId = 10,
                            RoleId = 4
                        },
                        new
                        {
                            UserId = 11,
                            RoleId = 4
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Value")
                        .HasColumnType("longtext");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("DorucovaciSluzba.Domain.Entities.PackageHistoryItem", b =>
                {
                    b.HasOne("DorucovaciSluzba.Domain.Entities.StavZasilka", "Stav")
                        .WithMany()
                        .HasForeignKey("StavId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Stav");
                });

            modelBuilder.Entity("DorucovaciSluzba.Domain.Entities.Zasilka", b =>
                {
                    b.HasOne("DorucovaciSluzba.Infrastructure.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("KuryrId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DorucovaciSluzba.Infrastructure.Identity.User", null)
                        .WithMany("OdeslaneZasilky")
                        .HasForeignKey("OdesilatelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DorucovaciSluzba.Infrastructure.Identity.User", null)
                        .WithMany("PrijateZasilky")
                        .HasForeignKey("PrijemceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DorucovaciSluzba.Domain.Entities.StavZasilka", "Stav")
                        .WithMany()
                        .HasForeignKey("StavId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DorucovaciSluzba.Infrastructure.Identity.User", null)
                        .WithMany("DorucovaciZasilky")
                        .HasForeignKey("UserId");

                    b.Navigation("Stav");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("DorucovaciSluzba.Infrastructure.Identity.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("DorucovaciSluzba.Infrastructure.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("DorucovaciSluzba.Infrastructure.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.HasOne("DorucovaciSluzba.Infrastructure.Identity.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DorucovaciSluzba.Infrastructure.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("DorucovaciSluzba.Infrastructure.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DorucovaciSluzba.Infrastructure.Identity.User", b =>
                {
                    b.Navigation("DorucovaciZasilky");

                    b.Navigation("OdeslaneZasilky");

                    b.Navigation("PrijateZasilky");
                });
#pragma warning restore 612, 618
        }
    }
}
