// <auto-generated />
using System;
using DorucovaciSluzba.Infrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DorucovaciSluzba.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251025143635_mysql_init")]
    partial class mysql_init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("DorucovaciSluzba.Domain.Entities.StavZasilka", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Stav")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("StavZasilka");
                });

            modelBuilder.Entity("DorucovaciSluzba.Domain.Entities.TypUzivatel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Typ")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("TypUzivatel");
                });

            modelBuilder.Entity("DorucovaciSluzba.Domain.Entities.Uzivatel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DatumNarozeni")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Heslo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Jmeno")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Mesto")
                        .HasColumnType("longtext");

                    b.Property<string>("Prijmeni")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Psc")
                        .HasColumnType("longtext");

                    b.Property<string>("Telefon")
                        .HasColumnType("longtext");

                    b.Property<int>("TypId")
                        .HasColumnType("int");

                    b.Property<string>("Ulice")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("TypId");

                    b.ToTable("Uzivatel");
                });

            modelBuilder.Entity("DorucovaciSluzba.Domain.Entities.Zasilka", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Cislo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("DatumOdeslani")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime(6)");

                    MySqlPropertyBuilderExtensions.UseMySqlComputedColumn(b.Property<DateTime>("DatumOdeslani"));

                    b.Property<string>("DestinaceMesto")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("DestinacePsc")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("DestinaceUlice")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("KuryrId")
                        .HasColumnType("int");

                    b.Property<int>("OdesilatelId")
                        .HasColumnType("int");

                    b.Property<int>("PrijemceId")
                        .HasColumnType("int");

                    b.Property<int>("StavId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("KuryrId");

                    b.HasIndex("OdesilatelId");

                    b.HasIndex("PrijemceId");

                    b.HasIndex("StavId");

                    b.ToTable("Zasilka");
                });

            modelBuilder.Entity("DorucovaciSluzba.Domain.Entities.Uzivatel", b =>
                {
                    b.HasOne("DorucovaciSluzba.Domain.Entities.TypUzivatel", "Typ")
                        .WithMany()
                        .HasForeignKey("TypId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Typ");
                });

            modelBuilder.Entity("DorucovaciSluzba.Domain.Entities.Zasilka", b =>
                {
                    b.HasOne("DorucovaciSluzba.Domain.Entities.Uzivatel", "Kuryr")
                        .WithMany()
                        .HasForeignKey("KuryrId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DorucovaciSluzba.Domain.Entities.Uzivatel", "Odesilatel")
                        .WithMany("OdeslaneZasilky")
                        .HasForeignKey("OdesilatelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DorucovaciSluzba.Domain.Entities.Uzivatel", "Prijemce")
                        .WithMany("PrijateZasilky")
                        .HasForeignKey("PrijemceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DorucovaciSluzba.Domain.Entities.StavZasilka", "Stav")
                        .WithMany()
                        .HasForeignKey("StavId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kuryr");

                    b.Navigation("Odesilatel");

                    b.Navigation("Prijemce");

                    b.Navigation("Stav");
                });

            modelBuilder.Entity("DorucovaciSluzba.Domain.Entities.Uzivatel", b =>
                {
                    b.Navigation("OdeslaneZasilky");

                    b.Navigation("PrijateZasilky");
                });
#pragma warning restore 612, 618
        }
    }
}
